name: MonopolyGamerSoundboard
description: A soundboard for monopoly gamer table game.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  audioplayer:
  path_provider:
  flutter_launcher_icons: "^0.3.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/star.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bowser.mp3
    - assets/bowser.png
    - assets/victory.mp3
    - assets/victory.png
    - assets/coin.mp3
    - assets/coin.png
    - assets/star.mp3
    - assets/star.png
    - assets/pipe.mp3
    - assets/pipe.png
    - assets/dies.mp3
    - assets/dies.png
    - assets/background.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
      - family: emulogic
        fonts:
          - asset: fonts/emulogic.ttf
      - family: SuperMarioBrossWii
        fonts:
          - asset: fonts/SuperMarioBrosWii.otf
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
